### ISSUE TITLE
GOPATH

### ISSUE THREAD

**Issue by robfordww** [go-chi/docgen#20]
```
	goPath := os.Getenv("GOPATH")
	if goPath == "" {
		return d, errors.New("docgen: unable to determine your $GOPATH")
	}
```

Is this hard requirement, or can it be made to work without GOPATH as well?  I see that the rest example fails like this for me now:

```
> ./rest-example -routes
ERROR: docgen: unable to determine your $GOPATH
```

**Comment by Athosone** [comment]
Same here...
I wonder if that feature is still maintained

**Comment by alchemy** [comment]
My pull request #21 fixes this

**Comment by till** [comment]
Can someone tag `v1.0.6`?

**Comment by VojtechVitek** [comment]
tagged as v1.3.0
