### ISSUE TITLE
How to add other info like expected payloads for the url endpoints?

### ISSUE THREAD

**Issue by tonyalaribe** [go-chi/docgen#5]
Is there any approach for adding other information like expected payloads for the url endpoints?

**Comment by VojtechVitek** [comment]
We capture payloads in our E2E tests and store it into files named after routes. And then, we find the corresponding payloads in the docgen Walk() and put it into the RAML resource.

https://github.com/go-chi/docgen/blob/master/raml/raml_test.go#L29

**Comment by pkieltyka** [comment]
this isn't a goal of docgen
